config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :comments, only: [:new, :create, :index, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # No permissions for other users
    can :read, :all
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

    # additional permissions for administrators
    return unless user.present?

    # additional permissions for logged in users
    can :manage, Post, author: user
    can :manage, Comment, author: user
    can :manage, Like, author: user

    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  def increment_comment_counters
    post.increment!(:comments_counter)
  end

  def decrement_comment_counts
    return unless post.comments_counter.positive?

    post.decrement!(:comments_counter)
  end

  after_create :increment_comment_counters
  before_destroy :decrement_comment_counts
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  def increment_like_counts
    post.increment!(:likes_counter)
  end
  after_create :increment_like_counts
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, foreign_key: 'post_id', dependent: :destroy
  belongs_to :author, class_name: 'User'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def latest_comments
    comments.order(created_at: :desc).limit(5)
  end

  def increment_post_counts
    author.increment!(:post_counter)
  end

  def decrement_post_counts
    return unless author.post_counter.positive?

    author.decrement!(:post_counter)
  end

  after_create :increment_post_counts
  before_destroy :decrement_post_counts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :email, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def latest_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, null_session: true
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :authenticate_user!, if: :skip_authenticate_user
  skip_before_action :verify_authenticity_token, if: :skip_authenticate_user
  rescue_from ActiveRecord::RecordNotFound, with: :_private_record_not_found
  before_action :_private_validate_params

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio])
  end

  def skip_authenticate_user
    (request.format.json? || request.format.xml?)
  end

  def authenticate_api_request
    return @api_user ||= current_user unless request.format.json? || request.format.xml?

    auth_token = request.headers['x-api-key'] # for now this is the user id until JWT
    @api_user = User.find_by(id: auth_token)

    return render json: { error: 'Invalid token' }, status: :unauthorized unless @api_user || request.format.html?

    @api_user
  end

  def _private_record_not_found
    respond_to do |format|
      format.html { render 'errors/_404', locals: { value: 'The details no longer exist', header: true } }
      format.json { render json: { errors: 'The details no longer exist' }, status: :not_found }
    end
  end

  def _private_validate_params
    url_params = [(params[:user_id] || params[:id]), (params[:post_id] || params[:id]), params[:id]]
    user_id, post_id, comment_id = *url_params

    @user_id = Integer(user_id) unless user_id.nil?
    @post_id = Integer(post_id) unless post_id.nil?
    @comment_id = Integer(comment_id) unless comment_id.nil?
  rescue ArgumentError
    respond_to do |format|
      format.html { render 'errors/_404', locals: { value: 'The details no longer exist', header: true } }
      format.json { render json: { errors: 'The details no longer exist' }, status: :not_found }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_api_request, only: [:create]
  before_action :current_post

  def new
    @comment = Comment.new
  end

  def index
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comments = @post.comments

    respond_to do |format|
      format.html
      format.json { render json: @comments }
    end
  end

  def create
    current_user ||= @api_user
    @comments = @current_post.comments.new(comment_params)
    @comments.post_id = @current_post.id
    @comments.author_id = current_user.id

    if @comments.save
      return render json: @current_post.comments unless request.format.html?

      redirect_to "/users/#{@current_post.author_id}/posts/#{@current_post.id}"
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find_by(id: @comment_id, post_id: @post_id)
    return redirect_to "/users/#{@user_id}/posts/#{@post_id}" if @comment.destroy

    render 'errors/404', value: 'The comment no longer exists'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def current_post
    @current_post = Post.find(@post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  check_authorization
  skip_authorization_check
  before_action :current_post

  def new
    @like = Like.new
  end

  def create
    @like = @current_post.likes.new(author_id: current_user.id, post_id: @current_post.id)
    return redirect_to "/users/#{@current_post.author.id}/posts/#{@current_post.id}" if @like.save

    render.new
  end

  def current_post
    @current_post = Post.find(@post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  check_authorization
  skip_authorization_check

  def index
    @user = User.find(@user_id)
    @posts = @user.posts.includes(:comments)
    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(@post_id)
    # TODO: Add check to validate if the user_id in url matches the post author
    # Useless but its what we want to ensure post_author and current user in the url match
    # @post = nil unless @post.author.id == userid
    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save
      redirect_to "/users/#{current_user.id}/posts"
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(@post)
    return redirect_to "/users/#{current_user.id}/posts" if @post.destroy

    render 'errors/404', value: 'The post no longer exists'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  check_authorization
  skip_authorization_check

  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(@user_id)
    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/index.html.erb
<section class='posts detail post py-3'>
    <article class='comment'>
        <%= render "posts/shared/comments", comments: @post.comments %>
    </article>
</section>

app/views/comments/new.html.erb
<div class='pt-5 d-flex align-items-center flex-column'>
  <h4>Add your comment <%= %> </h4>
  <%= form_with model: @comment, url: user_post_comments_path do |form| %>
    <div class='mb-3'>
      <%= form.text_area :text, size:"50x3",placeholder: 'Like: great read', class:'form-control'%>
    </div>
    <%= form.submit "Submit", class:'btn btn-dark' %>
    <%= link_to "Cancel", user_post_path(user_id: @current_post.author.id, id: @current_post.id), class:"btn btn-default btn-outline-dark" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% unless notice.nil? %>
      <p class="notice alert alert-info" role="alert"><%= notice %></p>
    <% end %>
    <% unless alert.nil? %>
      <p class="alert alert-danger" role="alert"><%= alert %></p>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<% if @posts.nil? %>
    <%= render 'errors/404', value: 'The specified user has no created blog posts', header: true %>
<% else %>
    <section class='userlist'>
        <%= render 'shared/user', user: @user %>
    </section>

    <section class='userlist'>
        <div class ="d-flex align-items-center justify-content-between">
            <h4>Posts</h4>
            <%= link_to "Create post", new_user_post_path(user_id: @user.id), class:"btn btn-outline-dark btn-default" %>
        </div>
    </section>
    <%= render "shared/posts", user: @user, posts: @posts, view_more: false %>
    <% if @posts.length > 0 %>
        <div class="links">
            <div class="button-links">
                <%= link_to "Pagination", user_posts_path(user_id: @user.id) %>
            </div>
        </div>
    <% end %>
<% end %>

app/views/posts/new.html.erb
<%# Has a form to add a new post %>
<div class='mt-3 d-flex align-items-center flex-column'>
    <h4>Create a new blog post</h4>
    <%= bootstrap_form_with(model: @post, local: true, class: 'w-100 container', url: user_posts_path) do |form| %>
        <%= form.text_field :title %>
        <%= form.text_area :text %>
        <%= form.submit "Submit" %>
        <%= link_to "cancel", user_posts_path(user_id: current_user.id), class:"btn btn-default btn-outline-dark" %>
    <% end %>
</div>

app/views/posts/shared/_comments.html.erb
<%# Show the details about the comments by a user %>
<% if comments.empty? %>
    <%= render 'errors/404', value: 'There are no comments for this blog post' %>
<% else %>
    <div class="body">
        <% comments.includes([:author]).each do | comment | %>
            <div class="d-flex flex-column">
                <%= comment.author.name %>: <%= comment.text %>
                <% if can? :destroy, comment %>
                    <a class="ml-auto">
                        <%= button_to user_post_comment_path(user_id: comment.post.author_id, post_id: comment.post_id, id: comment.id), method: :delete, class: 'btn btn-default btn-outline-dark', data: { confirm: 'Are you sure?' } do %>
                            <i class="fas fa-trash-alt"></i>
                        <% end %>
                    </a>
                <% end %>
            </div>
        <% end %>
    </div>
<% end %>

app/views/posts/show.html.erb
<% 
    post = @post rescue nil
    if post.nil? 
%>
    <%= render 'errors/404', value: 'There blog post specified by user does not exist', header: true %>
<% else %>
<section class='posts detail post'>
    <article class='post'>
        <div class="body">
            <div class="detail-header">
                <span><%= @post.title %> by <%= @post.author.name %></span>
                <span>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></span>
            </div>
            <p><%= @post.text %>
        </div>
    </article>
    <article class='comment'>
        <%= render "posts/shared/comments", comments: @post.comments %>
    </article>
    <div class="d-flex align-items-center justify-content-end">
        <%= link_to "Add Comment", new_user_post_comment_path(@post.author.id, @post.id), class:"btn btn-default btn-outline-dark mr-3" %>
        <div class="d-flex align-items-center">
            <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |f| %>
            <%= f.submit "Like", class:"btn btn-outline-dark" %>
            <% end %>
        </div>
    </div>
</section>
<% end %>

app/views/shared/_post.html.erb
<%# Renders a user detail %>
<article class='post'>
    <%= link_to user_post_path(user_id: post.author_id, id: post.id), class: 'd-block flex-column' do  %>
        <div class="body d-flex flex-column justify-content-start">
            <b><%= post.title %></b>
            <p><%= "#{post.text[0..157]}#{' ...' if post.text.length() > 157}" %></p>
            <div class="counter d-flex ml-auto align-items-center">
                Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %>
                <% if can? :destroy, post %>
                    <a><%= button_to user_post_path(user_id: post.author_id, id: post.id), method: :delete, class: 'ml-3 btn btn-default btn-outline-dark', data: { confirm: 'Are you sure?' } do %>
                        <i class="fas fa-trash-alt"></i>
                    <% end %>
                    </a>
                <% end %>
            </div>
        </div>
    <% end %>
</article>
<article class='comment'>
    <%= render "posts/shared/comments", comments: post.latest_comments %>
</article>

app/views/shared/_posts.html.erb
<%# Show posts of a user or no posts meessage %>
<% if posts.empty? %>
    <%= render 'errors/404', value: 'The user has not added any posts' %>
<% else %>
    <section class='posts'>
        <% posts.includes(:comments).each do | post | %>
            <%= render "shared/post", post: post %>
        <% end %>
    </section>
    <% if view_more %>
        <div class="links">
            <div class="button-links">
                <%= link_to "See all posts", user_posts_path(user_id: user) %>
            </div>
        </div>
    <% end %>
<% end %>

app/views/shared/_user.html.erb
<%# Renders a user detail %>
<article class='article'>
    <%= link_to user_path(id: user.id) do  %>
        <div class="image">
            <img src="<%= user.photo %>" alt="<%= user.name %>" />
        </div>
        <div class="body">
            <h4><%= user.name %></h4>
            <div class="counter position-absolute">Number of posts: <%= user.post_counter %></div>
        </div>
    <% end %>
</article>

app/views/users/index.html.erb
<% if @users.nil? || @users.empty? %>
    <%= render 'errors/404', value: 'There are no registered users at the moment', header: true %>
<% else %>
    <section class='userlist'>
        <% @users.each do | user | %>
            <%= render "shared/user", user: user %>
        <% end %>
    </section>
<% end %>

app/views/users/show.html.erb
<% if @user.nil? %>
    <%= render 'errors/404', value: 'There is no details about the specified user', header: true %>
<% else %>
    <section class='userlist'>
        <%= render 'shared/user', user: @user %>
    </section>
    <section class='bio'>
       <div class='body'>
        <b>Bio</b>
        <p><%= @user.bio %>
       </div>
    </section>
    <%= render "shared/posts", user: @user, posts: @user.latest_posts, view_more: true %>
<% end %>